name: "Auto build"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 2"

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1.1.1
      with:
        args: -X POST 'https://hub.docker.com/api/build/v1/source/fd350084-414d-4dcf-9bb8-258fe09f2d06/trigger/${{ secrets.DOCKER_TRIGGER }}/call/'
